image: maven:latest
# тест запуск
stages:
  - build
  - test
  - deploy


# Сборка 
build:
  stage: build
  script:
    - mvn clean install

# Тестирование 
test:
  stage: test
  script:
    - mvn test

# Развертывание 
deploy:
  stage: deploy
  script: 
    - mvn deploy -DDB_URL=$DB_URL -DDB_USERNAME=$DB_USERNAME -DDB_PASSWORD=$DB_PASSWORD -DBOT_TOKEN=$BOT_TOKEN -DSMTP_AUTH_USER=$SMTP_AUTH_USER -DSMTP_AUTH_PWD=$SMTP_AUTH_PWD -DSMTP_HOST_NAME=$SMTP_HOST_NAME -DSMTP_PORT=$SMTP_PORT -DMOCK_SERVER_URL=$MOCK_SERVER_URL
