image : gradle:latest 

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - gradle

build_job:
  stage: build
  tags:
    - docker
  script:
    - echo "Gradle build started"
    - "gradle clean check"

test_job:
  stage: test
  tags:
    - docker
  script:
    - echo "Gradle test started"
    - "gradle test"
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml


lint_job:
  stage: test
  tags:
    - docker
  script:
    - echo "Running linters"
    # - "gradle check"
  artifacts:
    when: always
    paths:
      - target/checkstyle-result.xml

package_job:
  stage: package
  tags:
    - docker
  script:
    - echo "Gradle packaging started"
    - "gradle build shadowJar"

deploy_job:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Gradle deploy started"
