version: "3.9"
services:

  bot:
    image: catorleader/bot:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d IUBookingBotDb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  db-data:
