version: "3.9"
services:
  postgres:
    image: postgres:15.0
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "IUBookingBotDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d IUBookingBotDb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  bot:
    image: catorleader/bot:latest
    container_name: bot
    environment:
      BOT_TOKEN: "6065382468:AAEWy7pzKrLu2teez_jtEyY_pXzQGWP5AsI"
      DB_PASSWORD: "admin"
      DB_URL: "jdbc:postgresql://localhost:5432/IUBookingBotDb"
      DB_USERNAME: "postgres"
      MOCK_SERVER_URL: "http://185.91.53.106"
      SMTP_AUTH_PWD: "6ILuphBJT8d7"
      SMTP_AUTH_USER: "sum23.swp.ubb.auth1@innopolis.university"
      SMTP_HOST_NAME: "mail.innopolis.ru"
      SMTP_PORT: "587"
      CONFIG_PATH: "/home/resources/properties.cfg"
    depends_on:
      - postgres
    network_mode: "host"